package com.grievance.portal.dto.response;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Authentication response — returned by login and register endpoints.
 *
 * Equivalent to Express auth response:
 *   res.json({ token: "JWT...", user: { id, name, email, role, ... } })
 *
 * React AuthContext stores:
 *   - token → localStorage ('token') → sent as Authorization: Bearer <token>
 *   - user → AuthContext state (id, name, role, etc.)
 *
 * This exact shape must be preserved for frontend compatibility.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class AuthResponse {

    /**
     * JWT token — stored by React in localStorage and sent with every request.
     * Generated by JwtUtil.generateToken(userId, role)
     */
    private String token;

    /**
     * Safe user object — stored in React AuthContext state.
     * Does NOT contain password.
     */
    private UserResponse user;
}
